//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKiNhom5_SimpleNote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note_Backup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note_Backup()
        {
            this.User_Note_Backup = new HashSet<User_Note_Backup>();
        }
    
        public int ID { get; set; }
        public string Header { get; set; }
        public string Context { get; set; }
        public string Time { get; set; }
        public string TimeEdit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Note_Backup> User_Note_Backup { get; set; }
    }
}
