//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKiNhom5_SimpleNote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note_Tag
    {
        public int ID { get; set; }
        public string MiniTag { get; set; }
        public string Description { get; set; }
    
        public virtual Note Note { get; set; }
    }
}
